name: docs
channels:
  #  - defaults
dependencies:
    # Base depends
  - python
  - pip
    
    # 
  - numpy
  - pandas
  - pennylane
  - scikit-learn
  - trimap
  - pacmap
  - seaborn
  - matplotlib
  - sphinx
  - sphinx_rtd_theme
  - mock
  - pillow
  
  # pip only installs
  - pip:
    - recommonmark
    - readthedocs-sphinx-ext

