name: docs
channels:
#  - defaults
dependencies:
  # Base depends
  - python
  - pip
    
  # packages used
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - sphinx
  - sphinx_rtd_theme
  - mock
  - pillow
  
  # pip only installs
  - pip:
    - scipy
    - pennylane
    - trimap
    - pacmap
    - recommonmark
    - readthedocs-sphinx-ext

