name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - pandas
  - pennylane
  - scikit-learn
  - trimap
  - pacmap
  - seaborn
  - matplotlib
  - sphinx
  - sphinx_rtd_theme

    # Pip-only installs
  #- pip:

